name: 错误报告
description: 如果一个功能未及预期, 或是出现了明显的错误, 则使用此模版.
title: "[BUG/CN] <填写一个简练的标题。不要动开头的标签。>"
labels: New
assignees: []
body:
  - type: textarea
    id: main_input
    attributes:
      label: 在这里根据模板填写对应必要的信息。你可以直接按<>/[]内的内容提示来将你的具体情况覆盖进去。
      value: |

        > 在开始之前, 你必须明确: 你使用的是当前通道最新版本的LauncherX, 并且你的问题在所有议题中没有重合, 并且在CSKB的常见问题中没有现成的解决方案.

        ## 问题说明
        *// 简要描述出现了什么问题. 一条议题仅能反馈一个问题或属于一个功能的问题, 太宽泛的多个问题必须分为多个议题分别提交*

        这个问题出现的概率有多大? `(0~100)`%

        ## 前提
        - 你使用的LauncherX版本号为? [在这里填写「设置-关于-二进制版本」的版本号]
        - 你的操作系统是什么版本? [在这里填写操作系统大版本、具体版本号、体系结构]
        - 涉及有具体的游戏吗? 如果是整合包, 提供整合包下载链接. [填入游戏版本号/整合包链接/或不填]

        ## 复现步骤
        执行这些操作, 有概率 (或是绝对) 出现上述的问题:

        *示例:*
        1. 在 '...' 前提下
        2. 打开 '....' 界面
        3. 找到 '....', 然后点击 ‘...’
        4. ‘...’
        5. 出现错误.

        ## 预期行为
        *根据你对界面和功能的理解, LauncherX本来应该完成什么工作?*

        ## 相关线索
        ### 日志
        *前往CSKB查阅获取相关日志的方法: https://kb.corona.studio/zhCN/lxguide/report-issue.html#%E5%8F%A6%E5%A4%96-%E5%93%AA%E4%BA%9B%E7%94%A8%E4%BA%8E%E5%8F%8D%E9%A6%88%E7%9A%84%E4%BF%A1%E6%81%AF%E6%98%AF%E6%9C%89%E7%94%A8%E7%9A%84-%E8%AF%A5%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E6%9C%89%E7%94%A8%E7%9A%84%E4%BF%A1%E6%81%AF *

        1. 
        ````` logs
        // 将这里替换为你找到的日志. 使用代码块包裹不同文件内保存的日志并标注文件名, 或者使用 mclo.gs 上传日志到云端.
        `````

        ### 截图和录屏
        *直接上传/粘贴在这里就好*

#        
  - type: textarea
    id: additional
    attributes: 
      label: 附加信息
      value: 其他相关内容写在这里. 如果你在LauncherX交流群中，可以在这里留下你的群昵称，以便我们发起实时问询。
  
#
  - type: checkboxes
    id: prerequisites
    attributes:
      label: 选项
      description: 在提交前请确认以下事项
      options:
        - label: 我已搜索过现有议题，没有找到相似的议题
          required: true
        - label: 我确认我的LauncherX符合系统体系结构，与我的设备和系统兼容，并且已经更新到当前通道的最新版本
          required: true
        - label: 我希望在交流群进行问询
