name: Bug Report
description: If any function is not meeting your expect, or obviously here's some bug or problem, use this template.
title: "[BUG/EN] <Replace this with a brief title and keep the [tag] remain.>"
labels: New
assignees: []
body:
  - type: textarea
    id: main_input
    attributes:
      label: Fill in the template - Replace the content wrapped with <>/[] to your situation.
      value: |

        > Before we start, you need to make sure: You're using the latest version of LauncherX in your channel, and your issue is not duplicated, meanwhile here's no solution on CSKB.

        ## Describe the problem
        *// Briefly describe your problem. If your problem is related to multiple functions, or too vast, please open issues one by one.*

        How frequent does the problem happen? `(0~100)`%

        ## Essentials
        - Which version of LauncherX you're using? [Fill in the number series from「Settings-About-Binary Version」which refers to a version number]
        - What kind of your operating system? Which version? [OS Name, Detailed Version, Architecture]
        - Is this related to a specific game? You can upload a zipped version directory/Link to the modpack/Game Version. []

        ## How to reproduce
        Following the following steps, here's a chance/ or absolutely will make the problem happen:

        *example*
        1. In '...' as a premise
        2. open view '....' 
        3. find out / goto '....', and then click ''
        4. '...'
        5. Here we go! the problem.

        ## Expected behaviour
        *According to your understanding of the shown function, what should LauncherX perform?*

        ## Related papertrails 
        ### Logs
        *How to find useful logs (CSKB, Chinese): https://kb.corona.studio/zhCN/lxguide/report-issue.html#%E5%8F%A6%E5%A4%96-%E5%93%AA%E4%BA%9B%E7%94%A8%E4%BA%8E%E5%8F%8D%E9%A6%88%E7%9A%84%E4%BF%A1%E6%81%AF%E6%98%AF%E6%9C%89%E7%94%A8%E7%9A%84-%E8%AF%A5%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E6%9C%89%E7%94%A8%E7%9A%84%E4%BF%A1%E6%81%AF *

        1. [log file name, and where you find it]
        ````` logs
        // Replace here to your logs, or upload your logs to mclo.gs (or similar tools) and provide the shared link here.
        `````

        ### Screenshot or recordings
        *just paste them here, or cloud-drive links. the must-login cloud drives are prohibited.*

#        
  - type: textarea
    id: additional
    attributes: 
      label: Additional Info
      value: Write down any related additional info here. If you're in our official group chat, you can leave your ID here and we can start an instant asking here.
  
#
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Checklist
      description: 'Please make sure:'
      options:
        - label: I promise there's no duplication after I did the search in all existing issues.
          required: true
        - label: I'm sure that my LauncherX has updated to the latest version in my channel, and it's compatible to my system.
          required: true
        - label: I hope to receive an instant ask.
