name: Feature Request
description: Use this template if you want to request a new function!
title: "[FEAT/EN] <Replace this with a brief title and keep the [tag] remain.>"
labels: 
  - New
  - imagine / 设想
assignees: 
  - fr1g
body:
  - type: textarea
    id: main_input
    attributes:
      label: Fill in this template
      value: |
 
        > Before we start, you need to make sure: You're using the latest version of LauncherX in your channel, you're sure that this function is not presented yet (even after a look up on CSKB) or not good enough, and your issue is not duplicated, meanwhile this function will do helps to a specific group of users.

        ## What do you want exactly?
        *// Describe it. if it's too vast, submit multiple issues for all you want.*

        ## Why you need such a function?
        *// Is this really can bring you convenience or enhance your experience?*

        ## Referring to the function does, is this something can simplify your frequent action? Is that a function that must to be implemented by launcher?
        *// well, ask yourself pls. If you even cannot persuade yourself, then won't persuade us.*

        ## Optional Illustration / Pcturesigns
        *// Paste your HTML-UI-Design/Not Too Abstracted sketch/Screenshot of LauncherX with your signs that describes your thoughts*

#        
  - type: textarea
    id: additional
    attributes: 
      label: Additional
      value: Write down any related additional info here. If you're in our official group chat, you can leave your ID here and we can start an instant asking here.
  
#
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Checklist
      description: 'Please make sure:'
      options:
        - label: I promise there's no duplication after I did the search in all existing issues.
          required: true
        - label: I'm sure that my LauncherX has updated to the latest version in my channel, and it's compatible to my system.
          required: true
        - label: I hope to receive an instant ask.
